### ISSUE TITLE
Question about Licencing

### ISSUE THREAD

**Issue by alexjnim** [chriskhanhtran/bert-summarization#5]
Hello Chris, 

My name is Alex and I work for an NLP startup in London, UK. 

We have been exploring extractive summarization with BERT models and were interested in your code. However, we could not find any license for this project.

As you've pointed out, you've modified the source code in [PreSumm](https://github.com/nlpyang/PreSumm) to use the HuggingFace's transformers library and their pre-trained DistilBERT model.

[PreSumm](https://github.com/nlpyang/PreSumm) has a specified MIT license.
I don't have a strong legal background to understand if your project would be automatically considered under MIT given that it's a modification of MIT licensed code (i.e. PreSumm). 

Would you mind specifying the type of licensing for your project? As we may consider using your code for commercial purposes. 

Thank you very much in advance!

**Comment by chriskhanhtran** [comment]
Thanks for reaching out to me. This repository is also under the MIT license.
